const STATUS_INTERNAL_SERVER_ERROR = 500;
const STATUS_OK = 200;
const STATUS_NOT_FOUND = 404;
const STATUS_CONFLICT = 409;
const STATUS_CREATED = 201;
const STATUS_NO_CONTENT = 204;
const STATUS_UNPROCESSABLE_ENTITY = 422;

module.exports = {
  STATUS_INTERNAL_SERVER_ERROR,
  STATUS_OK,
  STATUS_NOT_FOUND,
  STATUS_CONFLICT,
  STATUS_CREATED,
  STATUS_NO_CONTENT,
  STATUS_UNPROCESSABLE_ENTITY,
};